window:
  width: 1600
  height: 1600
  render_distance: 8

field:
  chunk_size: 16
  loading_distance: 5
  map_radius: 64
  generation:
    rock_proba: 0.05
    tree_proba: 0.07
    iron_proba: 0.2
    diamond_proba: 0.05
    structures:  # spawn probabilities are per chunk
      robot_proba: 0.1
  from_test_chunk: false

pathing:
  a_star_radius: 20
  default_detour: 10
  towards_player_radius: 
    early: 35
    usual: 45
    red_moon: 55

mobs:
  spawning:
    initial_hostile_per_chunk: 0.2
    base_day_amount: 2
    base_night_amount: 5
    increase_amount_every: 3  # in days
    max_mobs_on_chunk: 3
    hard_mobs_since: 3  # in days. hard mobs don't spawn before this
    probabilities:
      bane: 0.25
      ling: 0.2
      gelatinous_cube: 0.1
      # the rest is zombie

player:
  max_hp: 100
  cheating_start: true
  arrow_break_chance: 0.3

save_folder: game_saves
